# Generated by Django 2.2.5 on 2019-09-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='commoditytag',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='notice',
            managers=[
            ],
        ),
    ]
