# Generated by Django 2.2.4 on 2019-10-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commodity.Specification'),
        ),
    ]
