# Generated by Django 2.2.4 on 2019-10-21 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0002_auto_20191020_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='地区名称（省市区县）')),
                ('level', models.IntegerField(choices=[(1, '省'), (2, '市'), (3, '区/县')], default=1, verbose_name='级别')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subarea', to='mine.Area', verbose_name='上级地区')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(auto_now_add=True, verbose_name='gmt create')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='gmt modified')),
                ('delete_status', models.PositiveSmallIntegerField(blank=True, choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='删除状态')),
                ('default', models.BooleanField(default=False, verbose_name='是否默认地址')),
                ('receiver', models.CharField(max_length=32, verbose_name='收货人')),
                ('addr', models.CharField(max_length=64, verbose_name='详细地址')),
                ('phone', models.CharField(max_length=16, verbose_name='手机号')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='mine.Area', verbose_name='区/县')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='mine.Area', verbose_name='城市')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='mine.Area', verbose_name='省份')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
