# Generated by Django 2.2.4 on 2019-10-22 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commodity', '0007_auto_20191022_1832'),
        ('mine', '0003_area_shippingaddr'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(auto_now_add=True, verbose_name='gmt create')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='gmt modified')),
                ('delete_status', models.PositiveSmallIntegerField(blank=True, choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='删除状态')),
                ('used', models.BooleanField(default=False, verbose_name='是否使用')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
