# Generated by Django 2.2.4 on 2019-10-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_commoditycollect'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='pic',
            field=models.URLField(null=True, verbose_name='图'),
        ),
        migrations.AddField(
            model_name='specification',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.12, max_digits=15, verbose_name='价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specification',
            name='stocks',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
    ]
