# Generated by Django 2.2.4 on 2019-10-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_auto_20191019_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='pic',
            field=models.URLField(default=None, null=True, verbose_name='图'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='价格'),
        ),
    ]
